name: deploy

on:
  workflow_run:
    workflows: ['Hello World Pipeline']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker compose down &&
            docker compose pull &&
            docker compose up -d --remove-orphans